config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', registration: 'register', sign_up: 'signup' }


  root to: 'orchestras#index'

  resources :orchestras do
    resources :concerts
    resources :conductors
    resources :sections do
      resources :musicians
    end
  end
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  validates :location,
            :date, presence: true
  
  belongs_to :orchestra
end

app/models/conductor.rb
class Conductor < ActiveRecord::Base
  validates :first_name,
            :last_name,
            :date_joined, presence: true

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :orchestra_id, uniqueness: true

  belongs_to :orchestra
end

app/models/musician.rb
class Musician < ActiveRecord::Base
  validates :first_name,
            :last_name,
            :instrument,
            :date_joined,
            :email, presence: true
            
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :is_section_leader, :uniqueness => { :scope => :section_id }, :if => :is_section_leader

  belongs_to :section
end

app/models/orchestra.rb
class Orchestra < ActiveRecord::Base
  validates :title,
            :location,
            :date_founded, presence: true

  has_many :sections, dependent: :destroy
  has_many :musicians, through: :sections
  has_many :concerts, dependent: :destroy
  has_one  :conductor, dependent: :destroy
  
  belongs_to :user
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :title, presence: true

  has_many :musicians, dependent: :destroy
  
  belongs_to :orchestra
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :orchestras, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]
  before_action :set_orchestra

  def new
    @concert = Concert.new
  end

  def edit
  end

  def create
    @concert = Concert.new(concert_params)
    if @concert.save
      redirect_to orchestra_concert_path(@orchestra, @concert)
    else
      render :new
    end
  end

  def update
    if @concert.update(concert_params)
      redirect_to orchestra_concert_path(@orchestra, @concert)
    else
      render :edit
    end
  end

  def destroy
    @concert.destroy
    redirect_to orchestra_path(@orchestra)
  end

  private
    def set_concert
      @concert = Concert.find(params[:id])
    end

    def set_orchestra
      @orchestra = Orchestra.find(params[:orchestra_id])
    end

    def concert_params
      params.require(:concert).permit(:location, :date, :orchestra_id)
    end
end

app/controllers/conductors_controller.rb
class ConductorsController < ApplicationController
  before_action :set_conductor, only: [:show, :edit, :update, :destroy]
  before_action :set_orchestra

  def show
  end

  def new
    @conductor = Conductor.new
  end

  def edit
  end

  def create
    @conductor = Conductor.new(conductor_params)
    if @conductor.save
      redirect_to orchestra_conductor_path(@orchestra, @conductor), notice: 'Conductor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @conductor.update(conductor_params)
      redirect_to orchestra_path(@orchestra), notice: 'Conductor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @conductor.destroy
    redirect_to orchestra_path(@orchestra), notice: 'Conductor was successfully destroyed.'
  end

  private

    def set_conductor
      @conductor = Conductor.find(params[:id])
    end

    def set_orchestra
      @orchestra = Orchestra.find(params[:orchestra_id])
    end

    def conductor_params
      params.require(:conductor).permit(:first_name, :last_name, :email, :date_joined, :orchestra_id)
    end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  before_action :set_musician, only: [:show, :edit, :update, :destroy]
  before_action :set_orchestra
  before_action :set_section

  def show
  end

  def new
    @musician = Musician.new
  end

  def edit
  end

  def create
    @musician = Musician.new(musician_params)
    if @musician.save
      redirect_to orchestra_section_musician_path(@orchestra, @section, @musician), notice: 'Musician was successfully created.'
    else
      render :new
    end
  end

  def update
    if @musician.update(musician_params)
      redirect_to orchestra_section_musician_path(@orchestra, @section, @musician), notice: 'Musician was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @musician.destroy
    redirect_to orchestra_section_path(@orchestra, @section), notice: 'Musician was successfully destroyed.'
  end

  private
    def set_musician
      @musician = Musician.find(params[:id])
    end

    def set_section
      @section = Section.find(params[:section_id])
    end

    def set_orchestra
      @orchestra = Orchestra.find(params[:orchestra_id])
    end

    def musician_params
      params.require(:musician).permit(:first_name, :last_name, :email, :instrument, :is_section_leader, :date_joined, :section_id)
    end
end

app/controllers/orchestras_controller.rb
class OrchestrasController < ApplicationController
  before_action :set_orchestra, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /orchestras
  # GET /orchestras.json
  def index
    @orchestras = Orchestra.where(user_id: current_user.id)
  end

  # GET /orchestras/1
  def show
    @sections = @orchestra.sections.order(:title)
    @concerts = @orchestra.concerts.order(:date)
  end

  # GET /orchestras/new
  def new
    @orchestra = Orchestra.new
  end

  # GET /orchestras/1/edit
  def edit
  end

  # POST /orchestras
  def create
    @orchestra = Orchestra.new(orchestra_params)

    if @orchestra.save
      redirect_to @orchestra, notice: 'Orchestra was successfully created.'
    else
      render :new
    end

  end

  # PATCH/PUT /orchestras/1
  def update
    if @orchestra.update(orchestra_params)
      redirect_to @orchestra, notice: 'Orchestra was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orchestras/1
  def destroy
    @orchestra.destroy
    redirect_to orchestras_url, notice: 'Orchestra was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orchestra
      @orchestra = Orchestra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orchestra_params
      params.require(:orchestra).permit(:title, :kind, :location, :date_founded, :user_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :set_orchestra

  def show
    @musicians = @section.musicians.all.order(:last_name)
  end

  def new
    @section = Section.new
  end

  def edit
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to orchestra_path(@orchestra)
    else
      render :new
    end
  end

  def update
    if @section.update(section_params)
      redirect_to orchestra_section_path(@orchestra, @section), notice: 'Section was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to orchestra_path(@orchestra), notice: 'Section was successfully destroyed.'
  end

  private
    def set_section
      @section = Section.find(params[:id])
    end

    def set_orchestra
      @orchestra = Orchestra.find(params[:orchestra_id])
    end

    def section_params
      params.require(:section).permit(:title, :orchestra_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/conductors_helper.rb
module ConductorsHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/helpers/orchestras_helper.rb
module OrchestrasHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/concerts/_form.html.haml
= simple_form_for([@orchestra, @concert], html: {class: "form-horizontal"}) do |f|

  - if @concert.errors.any?
    #error_explanation
    - @concert.errors.full_messages.each do |message|
      .alert.alert-danger{:role => "alert"}
        %span.glyphicon.glyphicon-exclamation-sign
        %span= message

  .container
    .form-group
      = f.label :location, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :location, class: "form-control", placeholder: "Boston, MA"

    .form-group
      = f.label :date, class: "col-sm-2 control-label"
      .col-sm-8
        = f.date_select :date, start_year: 2016, class: "form-control"

    .form-group
      .col-sm-offset-2.col-sm-10
        -if @concert.new_record?
          = link_to "Back", orchestra_path(@orchestra), class: "btn btn-default"
        -else
          = link_to "Back", orchestra_concert_path(@orchestra, @concert), class: "btn btn-default"

        = f.submit class: "btn btn-success"

    = f.hidden_field :orchestra_id, value: params[:orchestra_id]

app/views/concerts/edit.html.haml
.page-header
  %h2.text-center Edit Concert

= render "form"

app/views/concerts/new.html.haml
.page-header
  %h2.text-center New Concert

= render "form"

app/views/conductors/_form.html.haml
= simple_form_for([@orchestra, @conductor], html: {class: "form-horizontal"}) do |f|

  - if @conductor.errors.any?
    #error_explanation
    - @conductor.errors.full_messages.each do |message|
      .alert.alert-danger{:role => "alert"}
        %span.glyphicon.glyphicon-exclamation-sign
        %span= message

  .container
    %p Fields with a * are required

    .form-group
      = f.label :first_name, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :first_name, class: "form-control", placeholder: "Wolfgang"

    .form-group
      = f.label :last_name, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :last_name, class: "form-control", placeholder: "Mozart"

    .form-group
      = f.label :email, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :email, class: "form-control", placeholder: "mozart@example.com"

    .form-group
      = f.label :date_joined, class: "col-sm-2 control-label"
      .col-sm-8
        = f.date_select :date_joined, class: "form-control"

    .form-group
      .col-sm-offset-2.col-sm-10
        -if @conductor.new_record?
          = link_to "Back", orchestra_path(@orchestra), class: "btn btn-default"
        -else
          = link_to "Back", orchestra_conductor_path(@orchestra, @conductor), class: "btn btn-default"
        = f.submit class: "btn btn-success"

    = f.hidden_field :orchestra_id, value: params[:orchestra_id]

app/views/conductors/edit.html.haml
.page-header
  %h2.text-center Edit Conductor
= render "form"

app/views/conductors/new.html.haml
.page-header
  %h2.text-center New Conductor
= render "form"

app/views/conductors/show.html.haml
.col-xs-12
  .page-header
    %h2.text-center
      = @conductor.first_name + " " + @conductor.last_name

.col-xs-12.col-sm-6
  .panel.panel-info
    .panel-heading
      %h4 Information
    %ul.list-group
      %li.list-group-item
        Email:
        %strong= @conductor.email
      %li.list-group-item
        Date Joined:
        %strong= @conductor.date_joined.strftime("%B %d, %Y")

.col-xs-12.col-sm-6
  = link_to "Back", orchestra_path(@orchestra), {class: "btn btn-default btn-block"}
  = link_to "Edit", edit_orchestra_conductor_path(@orchestra, @conductor), {class: "btn btn-warning btn-block"}
  = link_to "Delete", orchestra_conductor_path(@orchestra, @conductor), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-block"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Harmonize
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false
    = javascript_include_tag "application", "data-turbolinks-track" => false
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}

  %body
    .container
      .row
        .col-xs-12.bg-info
          .page-header
            %h1
              = link_to "Harmonize", root_path, class: "title"
              %br
              %small Orchestra management with style

        .col-xs-12
          -if user_signed_in?
            %span.lead.pull-left
              = "Hello, " + current_user.email
              = link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default"
        = yield

app/views/musicians/_form.html.haml
= simple_form_for([@orchestra, @section, @musician], html: {class: "form-horizontal"}) do |f|

  - if @musician.errors.any?
    #error_explanation
    - @musician.errors.full_messages.each do |message|
      .alert.alert-danger{:role => "alert"}
        %span.glyphicon.glyphicon-exclamation-sign
        %span= message

  .container
    %p Fields with a * are required

    .form-group
      = f.label :first_name, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :first_name, class: "form-control", placeholder: "Wolfgang"

    .form-group
      = f.label :last_name, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :last_name, class: "form-control", placeholder: "Mozart"

    .form-group
      = f.label :email, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :email, class: "form-control", placeholder: "mozart@example.com"

    .form-group
      = f.label :instrument, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :instrument, class: "form-control", placeholder: "Violin"

    .form-group
      = f.label :is_section_leader?, class: "col-sm-2 control-label"
      .col-sm-8
        = f.check_box :is_section_leader, class: "form-control"

    .form-group
      = f.label :date_joined, class: "col-sm-2 control-label"
      .col-sm-8
        = f.date_select :date_joined, class: "form-control"

    .form-group
      .col-sm-offset-2.col-sm-10
        -if @musician.new_record?
          = link_to "Back", orchestra_section_path(@orchestra, @section), class: "btn btn-default"
        -else
          = link_to "Back", orchestra_section_musician_path(@orchestra, @section, @musician), class: "btn btn-default"

        = f.submit class: "btn btn-success"

    = f.hidden_field :section_id, value: params[:section_id]

app/views/musicians/edit.html.haml
.page-header
  %h2.text-center Edit Musician

= render "form"

app/views/musicians/new.html.haml
.page-header
  %h2.text-center New Musician

= render "form"

app/views/musicians/show.html.haml
.col-xs-12
  .page-header
    %h2.text-center
      = @musician.first_name + " " + @musician.last_name
      - if @musician.is_section_leader?
        %span.glyphicon.glyphicon-music{"data-toggle": "tooltip", "data-placement": "top", "title": "Section Leader"}

.col-xs-12.col-sm-6
  .panel.panel-info
    .panel-heading
      %h4 Information
    %ul.list-group
      %li.list-group-item
        Instrument:
        %strong= @musician.instrument
      %li.list-group-item
        Email:
        %strong= @musician.email
      %li.list-group-item
        Date Joined:
        %strong= @musician.date_joined.strftime("%B %d, %Y")

.col-xs-12.col-sm-6
  = link_to "Back", orchestra_section_path(@orchestra, @section), {class: "btn btn-default btn-block"}
  = link_to "Edit", edit_orchestra_section_musician_path(@orchestra, @section, @musician), {class: "btn btn-warning btn-block"}
  = link_to "Delete", orchestra_section_musician_path(@orchestra, @section, @musician), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-block"

app/views/orchestras/_form.html.haml
= simple_form_for(@orchestra, html: { class: "form-horizontal" }) do |f|

  - if @orchestra.errors.any?
    #error_explanation
    - @orchestra.errors.full_messages.each do |message|
      .alert.alert-danger{:role => "alert"}
        %span.glyphicon.glyphicon-exclamation-sign
        %span= message

  .container
    %p Fields with a * are required.

    .form-group
      = f.label :title, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :title, class: "form-control", placeholder: "Boston Symphony Orchestra"

    .form-group
      = f.label :kind, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :kind, class: "form-control", placeholder: "Symphony"

    .form-group
      = f.label :location, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :location, class: "form-control", placeholder: "Boston, MA"

    .form-group
      = f.label :date_founded, class: "col-sm-2 control-label"
      .col-sm-8
        = f.date_select :date_founded, start_year: 1840, class: "form-control"

    .form-group
      .col-sm-offset-2.col-sm-10
        -if @orchestra.new_record?
          = link_to "Back", orchestras_path, class: "btn btn-default"
        -else
          = link_to "Back", orchestra_path(@orchestra), class: "btn btn-default"

        = f.submit class: "btn btn-success"

    = f.hidden_field :user_id, value: current_user.id

app/views/orchestras/edit.html.haml
.page-header
  %h2.text-center Edit Orchestra

= render "form"

app/views/orchestras/index.html.haml
.col-xs-12
  .page-header
    %h2.text-center
      Orchestras
      = link_to "New Orchestra", new_orchestra_path, :class => "btn btn-success btn-lg"

- @orchestras.each do |orchestra|
  .col-xs-12.col-sm-6.text-center
    .panel.panel-primary
      .panel-heading
        %h2.panel-title
          = orchestra.title
          %br
          = orchestra.date_founded.strftime("%B %d, %Y")
      .panel-body
        %h4
          = orchestra.location
        %h4
          = orchestra.sections.count
          = "Sections"
        %h4
          = orchestra.musicians.count
          = "Musicians"
        %h4
          = orchestra.concerts.count
          = "Concerts"
        .btn-group{role: "group"}
          = link_to "View", orchestra, class: "btn btn-info"
          = link_to "Edit", edit_orchestra_path(orchestra), class: "btn btn-warning"

app/views/orchestras/new.html.haml
.page-header
  %h2.text-center New Orchestra

= render "form"

app/views/orchestras/show.html.haml
.col-xs-12
  .page-header
    %h2.text-center= @orchestra.title

.col-xs-12.col-sm-7
  .panel.panel-info
    .panel-heading
      %h4 Information

    %ul.list-group
      %li.list-group-item
        Kind:
        %strong= @orchestra.kind
      %li.list-group-item
        Located in:
        %strong= @orchestra.location
      %li.list-group-item
        Date founded:
        %strong= @orchestra.date_founded.strftime("%B %d, %Y")
      %li.list-group-item.clearfix
        Conductor:
        - if @orchestra.conductor
          %strong= link_to @orchestra.conductor.first_name + " " + @orchestra.conductor.last_name, orchestra_conductor_path(@orchestra, @orchestra.conductor)
        - else
          %strong None!
          = link_to "Add a Conductor", new_orchestra_conductor_path(@orchestra), {class: "btn btn-success pull-right"}

.col-xs-12.col-sm-5
  .panel.panel-primary
    .panel-heading.clearfix
      %span.h4.pull-left Sections
      = link_to "Add a Section", new_orchestra_section_path(@orchestra), {class: "btn btn-success pull-right"}

    .list-group
      - if @sections.count >= 1
        - @sections.each do |section|
          = link_to (section.title + ": " + section.musicians.count.to_s), orchestra_section_path(@orchestra, section), {class: "list-group-item"}
      - else
        %li.list-group-item This orchestra has no sections.

.col-xs-12.col-sm-7
  .panel.panel-primary
    .panel-heading.clearfix
      %span.h4.pull-left Concerts
      = link_to "Add a Concert", new_orchestra_concert_path(@orchestra), {class: "btn btn-success pull-right"}

    .list-group
      - if @concerts.count >= 1
        - @concerts.each do |concert|
          %li.list-group-item.clearfix
            %p.reduce-width
              = concert.location + " – " + concert.date.strftime("%B %d, %Y").to_s
            .btn-group.pull-right{:role => "group"}
              = link_to "Edit", edit_orchestra_concert_path(@orchestra, concert), class: "btn btn-warning"
              = link_to "Delete", orchestra_concert_path(@orchestra, concert), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"
      - else
        %li.list-group-item This orchestra has no concerts.

.col-xs-12.col-sm-5
  = link_to "Back", orchestras_path, {class: "btn btn-default btn-block"}
  = link_to "Edit", edit_orchestra_path(@orchestra), {class: "btn btn-warning btn-block"}
  = link_to "Delete", orchestra_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-block"

app/views/sections/_form.html.haml
= simple_form_for([@orchestra, @section], html: {class: 'form-horizontal'}) do |f|

  - if @section.errors.any?
    #error_explanation
    - @section.errors.full_messages.each do |message|
      .alert.alert-danger{:role => "alert"}
        %span.glyphicon.glyphicon-exclamation-sign
        %span= message

  .container
    .form-group
      = f.label :title, class: "col-sm-2 control-label"
      .col-sm-8
        = f.text_field :title, class: "form-control", placeholder: "Strings, Brass, Woodwind, etc."


    .form-group
      .col-sm-offset-2.col-sm-8
        -if @section.new_record?
          = link_to "Back", orchestra_path(@orchestra), class: "btn btn-default"
        -else
          = link_to "Back", orchestra_section_path(@orchestra, @section), class: "btn btn-default"

        = f.submit class: "btn btn-success"

    = f.hidden_field :orchestra_id, value: params[:orchestra_id]

app/views/sections/edit.html.haml
.page-header
  %h2.text-center Edit Section

= render "form"

app/views/sections/new.html.haml
.page-header
  %h2.text-center New Section

= render "form"

app/views/sections/show.html.haml
.col-xs-12
  .page-header
    %h2.text-center= @section.title + " Section"

.col-xs-12.col-sm-6
  .panel.panel-primary
    .panel-heading.clearfix
      %span.h4.pull-left Musicians
      = link_to "Add a Musician", new_orchestra_section_musician_path(@orchestra, @section), {class: "btn btn-success pull-right"}

    .list-group
      - if @musicians.count >= 1
        - @musicians.each do |musician|
          -if musician.is_section_leader?
            = link_to (musician.first_name + " " + musician.last_name + " – " + musician.instrument), orchestra_section_musician_path(@orchestra, @section, musician), {class: "list-group-item list-group-item-success", "data-toggle": "tooltip", "data-placement": "top", "title": "Section Leader"}
          -else
            = link_to (musician.first_name + " " + musician.last_name + " – " + musician.instrument), orchestra_section_musician_path(@orchestra, @section, musician), {class: "list-group-item"}
      - else
        %li.list-group-item This section has no musicians.

.col-xs-12.col-sm-6
  = link_to "Back", orchestra_path(@orchestra), {class: "btn btn-default btn-block"}
  = link_to "Edit", edit_orchestra_section_path(@orchestra, @section), {class: "btn btn-warning btn-block"}
  = link_to "Delete", orchestra_section_path(@orchestra, @section), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-block"